/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://pyijvt4mnbdftadmc5wp7wslue.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-euxm4iwkd5aftgkgovvfms6vee",
    "aws_cognito_identity_pool_id": "us-west-2:088883fc-fc51-485b-a4a6-a1df65929c7d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Tz0ORDgKV",
    "aws_user_pools_web_client_id": "7194rft38o29mlq2guktkhto17",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    }
};


export default awsmobile;
